### ISSUE TITLE
发生IDE错误

### ISSUE THREAD

**Issue by svher** [hadix-lin/ideavim_extension#84] opened 2022-02-21 02:21 UTC
版本信息：
Goland 2021.3.3
IdeaVim 1.10.0
IdeaVimExtension 1.5.0

```
java.lang.ClassCastException: class com.maddyhome.idea.vim.newapi.IjVimEditor cannot be cast to class com.intellij.openapi.editor.Editor (com.maddyhome.idea.vim.newapi.IjVimEditor is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @7f6f4a8b; com.intellij.openapi.editor.Editor is in unnamed module of loader com.intellij.util.lang.PathClassLoader @8bd1b6a)
	at io.github.hadixlin.iss.InputMethodAutoSwitcher$exitInsertModeListener$1.currentEditor(InputMethodAutoSwitcher.kt:74)
	at io.github.hadixlin.iss.InputMethodAutoSwitcher$exitInsertModeListener$1.commandFinished(InputMethodAutoSwitcher.kt:62)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.access$300(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.executeOrAddToQueue(MessageBusImpl.java:208)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:105)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:166)
	at com.sun.proxy.$Proxy84.commandFinished(Unknown Source)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandFinished(CoreCommandProcessor.java:278)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.finishCommand(CoreCommandProcessor.java:259)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.finishCommand(CommandProcessorImpl.java:34)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:225)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.maddyhome.idea.vim.helper.RunnableHelper.runReadCommand(RunnableHelper.kt:36)
	at com.maddyhome.idea.vim.KeyHandler.executeCommand(KeyHandler.kt:718)
	at com.maddyhome.idea.vim.KeyHandler.finishedCommandPreparation(KeyHandler.kt:245)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:231)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:125)
	at com.maddyhome.idea.vim.ui.ex.ExShortcutKeyAction.actionPerformed(ExShortcutKeyAction.kt:48)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:573)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:702)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:456)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:224)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by svher** [comment] 2022-02-21 02:23
忘记说了，MacOS Montery 12.2.1

**Comment by gaokun** [comment] 2022-02-21 02:53
Same issue

```
WebStorm 2021.3.2
Build #WS-213.6777.57, built on January 31, 2022
Runtime version: 11.0.13+7-b1751.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4

IdeaVIM (1.10.0)
```

**Comment by hadix-lin** [comment] 2022-02-21 04:27
same as #82 . please download [1.5.1](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.5.1/IdeaVimExtension.zip) and try it.

**Comment by hadix-lin** [comment] 2022-02-21 04:30
Duplicate of #82

**Comment by EXHades** [comment] 2022-02-22 10:06
Why not update to jetbrains plugins Marketplace？in review?

**Comment by hadix-lin** [comment] 2022-02-22 11:08
> 

yes

**Closed** 2022-02-23 02:20 UTC
Labels: duplicate
